### ISSUE TITLE
https://websub.net is not available due to certificate issues

### ISSUE THREAD

**Issue by larsgsvensson** [w3c/websub#160]
The [WebSub Recommendation](https://www.w3.org/TR/websub/) contains links to the latest [editors' draft](https://websub.net/draft) and to the [implementation report](https://websub.net/implementation-reports), both using https-URIs with the domain-name `websub.net`. Those links fail due to an invalid security certificate. The current certificate is only valid for `*.indieweb.org` and  `indieweb.org`.

**Comment by aaronpk** [comment]
Fixed, thanks. Just moved this to a new server and forgot the cert!
