### ISSUE TITLE
discovery of hub url order and https vs http 

### ISSUE THREAD

**Issue by euri10** [w3c/websub#162]
greetings,  I'm currently trying to implement a subscriber and got kind of "stuck" by the below

 in [8.2 part](https://www.w3.org/TR/2018/REC-websub-20180123/#subscriptions) it is said:
> First, subscribers SHOULD always favor the HTTPS URL for hubs (even if the URL is advertised as HTTP).

Add to that in the [discovery](https://www.w3.org/TR/2018/REC-websub-20180123/#discovery) section:

> When perfoming discovery, subscribers MUST implement all three discovery mechanisms in the following order, stopping at the first match:
> 
> Issue a GET or HEAD request to retrieve the topic URL. Subscribers MUST check for HTTP Link headers first.
> In the absence of HTTP Link headers, and if the topic is an XML based feed or an HTML page, subscribers MUST check for embedded link elements.

Now if you take for instance https://push-pub.appspot.com/feed, it has the following link headers:
`link: <http://pubsubhubbub.superfeedr.com>; rel="hub", <http://push-pub.appspot.com/feed>; rel="self"`

while in the content:
```
<link rel="self" type="application/atom+xml" href="http://push-pub.appspot.com/feed"/>
<link rel="alternate" type="text/html" href="/"/>
<link rel="hub" href="https://pubsubhubbub.superfeedr.com"/>
```

so you can see the hub url in that case is http in the headers, https in the content.

if I discover the hub url and stop at the 1st match I'll get the http url and that kind of contradicts 8.2 that tells me I should use https.

so should the discovery discover the http url and try to subscribe to https anyway ? or should the discovery not stop at first match and if content gives a https url override the 1st header match ?

**Comment by dissolve** [comment]
I believe you are conflating two different things.
8.2 simply says "if the URL is http://, you should prefer https://"

You are correct in following discovery steps and stopping at the first match, the link headers.
Then you apply 8.2 saying that you discovered a link, so its preferable to use the https:// version of that URL you discovered in the link header. (but you technically don't have to)

**Comment by euri10** [comment]
Ok that's clearer in my mind now thanks.

Maybe that's just me but I feel the discovery part may be slightly improved stating that "upgrade scheme" possibility.
