### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by julien51** [w3c/websub#52]
Ask @rhiaro for the right stuff to put in there.

**Comment by julien51** [comment]
Also @tonyg I think we'll need to ask you to agree to this because I have merged your changes. This is W3C policy that I overlooked... sorry :(

**Comment by aaronpk** [comment]
fyi https://github.com/blog/1184-contributing-guidelines

**Comment by tonyg** [comment]
OK, no worries; I'll keep an eye on this issue and take a look when there's something to look at.

**Comment by julien51** [comment]
👋 @rhiaro

**Comment by rhiaro** [comment]
Ongoing internal W3C legal discussion, stay tuned.

**Comment by aaronpk** [comment]
ping @rhiaro any updates?

**Comment by rhiaro** [comment]
Stiiiill working on it

**Comment by tantek** [comment]
Am I missing something here? This is not the first W3C github repo / project. Are there seriously no others with a CONTRIBUTING.md that we can re-use? If so, how has this not been everyone else's problem already?

I'm going to give this til next Tuesday for someone (of W3T) to point to some existing boilerplate or an FAQ on how this is already a solved problem (requires no new legal text), and if I don't hear an answer like that by then to resolve this, I will raise it to the AB as an urgent W3C-wide issue with the use of GitHub.

**Comment by dissolve** [comment]
A quick look through other w3c repos shows that a number of them use this
https://github.com/w3c/uievents/blob/gh-pages/CONTRIBUTING.md

**Comment by sandhawke** [comment]
It looks like the solution is https://www.w3.org/PATCHES.html

**Comment by julien51** [comment]
Thanks all! I'll just copy the PATCHES.html file above in the repo and see if there is a GH setting to force adding this file to any PR in a specific repo.
