### ISSUE TITLE
Clarify that Content-Type MUST or SHOULD be included in (un)subscription requests

### ISSUE THREAD

**Issue by tonyg** [w3c/websub#65]
In the 20 Oct draft, I see "This request has a Content-Type of application/x-www-form-urlencoded". I had overlooked this when building my implementation, which led to failures in interop testing with pubsub.rocks.

In fact, my first reading of the sentence in the spec is that it tells me how to format the body, but doesn't directly tell me anything about whether or which Content-Type header I should or must include. Perhaps strengthening this to a SHOULD or a MUST would help.

Concretely, I suggest revising the opening lines of the "Subscriber Sends Subscription Request" section to be:

> Subscription is initiated by the subscriber making an HTTPS or HTTP POST [[!RFC7231]] request to the hub URL. This request MUST have a Content-Type header of <samp>application/x-www-form-urlencoded</samp> (described in Section 17.13.4 of [[!W3C.REC-html401-19991224]]) and the following parameters in its body, formatted accordingly:

**Comment by julien51** [comment]
Do you mind submitting a PR? This makes it easier to see changes? Thanks!
