### ISSUE TITLE
Discovery: "exact" URL

### ISSUE THREAD

**Issue by cweiske** [w3c/websub#66]
The discovery section states:

> The former MUST indicate the exact URL of a WebSub hub designated by the publisher

What does "exact" mean in this case? Does it mean "absolute" or "full"?

Note that the web linking rfc allows relative URLs https://tools.ietf.org/html/rfc5988#section-5.1

> If the URI-Reference is relative, parsers MUST resolve it

**Comment by julien51** [comment]
This means `self`.

**Comment by cweiske** [comment]
ok.
