### ISSUE TITLE
Discovery: Limit HTML rel=hub links to <link> elements in <head> only.

### ISSUE THREAD

**Issue by cweiske** [w3c/websub#67]
if `<a rel="hub">` is allowed, then people could hijack the page's hub URL via the HTML comments box. " together with fat pings this would mean that I could inject fake news into people's readers when they susbcribe to someone's blog, just by posting a comment with a rel=hub link"

Please also note in the security considerations why implementations MUST NOT support `<a rel="hub">`

**Comment by dissolve** [comment]
This could be done with a <link rel="hub"> as well in HTML via a comments box.  Just limiting to head would probably work.  But I don't know how many people may already be using it in the body.  If not there needs to be a strongly worded warning about sanitizing external inputs to prevent such an attach vector specifically.

**Comment by cweiske** [comment]
A `<link>` may only be used in the body when it's [body-ok](https://html.spec.whatwg.org/multipage/semantics.html#body-ok). We'd not allow `<link rel=hub>` in body and the link extractors would not look in  the body at all.

**Comment by julien51** [comment]
Works for me! Please submit a PR :)

**Comment by cweiske** [comment]
ok.
