### ISSUE TITLE
Drop MUST requirement for rel=self

### ISSUE THREAD

**Issue by cweiske** [w3c/websub#69]
WebSub requires publishers to add a `rel=self` link to each document:

> The discovery mechanism aims at identifying at least 2 URLs.
> ...
> The canonical URL for the topic to which subscribers are expected to use for subscriptions.
> The protocol currently supports the following discovery mechanisms. Publishers MUST implement at least one of them:
> ...

Please drop the MUST requirement for the `rel=self` URL and let clients fall back to URL that was used to retrieve the document. This will make it easier to implement WebSub on the publisher side.

Also see the discussion in the #indieweb channel: https://chat.indieweb.org/2015-05-22#t1432330396549000

**Comment by voxpelli** [comment]
Do someone know the historical reason it was added in the first place?

**Comment by pfefferle** [comment]
here is the original discussion: https://github.com/pubsubhubbub/PubSubHubbub/issues/36

**Comment by cweiske** [comment]
I already forgot about that issue :/

**Comment by pfefferle** [comment]
rel-self is defined here btw. https://tools.ietf.org/html/rfc5988
