### ISSUE TITLE
https://www.w3.org/TR/pubsub/ should redirect to .../websub/

### ISSUE THREAD

**Issue by tonyg** [w3c/websub#71]
Now that the rename is complete, and a new draft is up (yay!), <https://www.w3.org/TR/pubsub/> should redirect to <https://www.w3.org/TR/websub/>.

**Comment by aaronpk** [comment]
It looks like it does, is that not what you see?

**Comment by tonyg** [comment]
**embarrassed** So I hear tell that one of the hard problems in CS is cache invalidation. Refreshing the page, rather than relying on my browser to detect that it had changed when I pasted the URL into the URL bar, caused it to update. Sorry for the noise!
