### ISSUE TITLE
Section 2, Bullet 3 is out of date

### ISSUE THREAD

**Issue by azaroth42** [w3c/websub#85]
The rest of the specification does not discuss the interactions between publisher and hub, but bullet 3 in section 2 describes the hub/publisher verification step of ensuring that the content did indeed change.

**Comment by julien51** [comment]
Are you referring to this section?

> The hub caches minimal metadata about each topic's previous state. When the hub re-fetches a topic (on its own initiative or as a result of a publisher's ping) and finds a difference, it enqueues a notification to all registered subscribers.

This section is non-normative... but I think you're right that there are too many details in there. I'd replace with:

> When the hub identifies a change in the topic, it performs a notification to all registered subscribers.

What do you think?

**Comment by azaroth42** [comment]
s/performs/sends/  ... but yes, that would be good IMO. Would consider the issue resolved after that change.
