### ISSUE TITLE
implementation report template missing

### ISSUE THREAD

**Issue by seebi** [w3c/websub#99]
please close this once the template is ready (so I get an email :) )

**Comment by aaronpk** [comment]
The subscriber implementation report is now in place, along with a complete test suite for the subscriber features.

https://github.com/w3c/websub/blob/master/implementation-reports/SUBSCRIBER-TEMPLATE.md

https://websub.rocks/subscriber

I'm going to leave this issue open until the other tests and report templates are complete.

**Comment by aaronpk** [comment]
Implementation reports (as well as the test suite) for the other roles are complete!
